[package]
name = "problem-1"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
cucumber = { version = "0.21.1" }
tokio    = { version = "1.42.0", features = ["full"] }

[[test]]
name = "main"
harness = false
